### ISSUE TITLE
Missing assets throughout tests

### ISSUE THREAD

**Issue by adamrt** [MorcilloSanz/RendererGL#111]
Hi I always checkout out cool renderers when I see them. I went to test RendererGL but the majority of the tests have hard links to models on your local machine ([example](https://github.com/MorcilloSanz/RendererGL/blob/main/test/testImGuiGLFW/src/main.cpp#L313)).

In the interest of not being lazy I tried to track them down and was going to create a PR, but I'm unable to find most of them. 

I was able to find [Block City](https://www.models-resource.com/gamecube/mariokartdoubledash/model/3162/), but most others weren't as obvious. Any change you will commit the assets to the repo and make the paths relative? Or if you zip up that models folder I'd be happy to send a PR with relative paths.

No worries either way. Very cool project!

**Comment by MorcilloSanz** [comment]
Hello, thank you very much for your words.

The main reason why I don't upload the test assets is because I don't know the origin of some of them and therefore their license.
For that reason I left the absolute paths, so that it serves as an example for the users.

In case it is useful, I downloaded most of them from https://www.models-resource.com
And in the case of the PBR test, I downloaded the textures from: https://freepbr.com

What I would do would be to download the ones I find most interesting and substitute the routes in the test. You can take advantage of the Block City model since you have found it.

Thanks in advance.

**Comment by adamrt** [comment]
Thanks Morcillo, that's helpful and makes a lot of sense about the license. I'll spend some time getting them going this weekend. Keep up the awesome work!
